# CS6493 - Tutorial 1
## Introduction to JupyterHub and PyTorch

Welcome to CS6493 tutorial. In this tutorial, you will get familiar with our exprimental environment, and also practice with some basic PyTorch operations.

## 1. JupyterHub

You can use the JupyterHub to run the toy models. Here are some notes for JupyterHub:

- You are supposed to be familiar with Python and Jupyter;

- You can use **Google Colab**
- Each student will be allocated with **8GB GPU memories**;
- Accommodate up to **60 students** to simultaneously use the JpuyterHub;
- **DO NOT** attempt to load large models, such as T5 and GPT-3 on JupyterHub;
- **DO NOT** run a program more than 1 week.

## 2. PyTorch

We use [PyTorch](https://pytorch.org/) framework to finish the implementations. In this section, we will introduce the installation, the basic operations of PyTorch.

### 2.1 Installation
Here, we install PyTorch with GPU supports. So, we first need to know the CUDA version in the server.

In [1]:
!nvidia-smi

Wed Jan 14 09:07:03 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   67C    P8             11W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

Then, we find the suitable version package from https://pytorch.org/. Past the command and run in the cell.

Here we choose the version 1.10.1 with CUDA 10.2.

In [2]:
!pip3 install torch torchvision torchaudio

Now we can check the version of our installed package and whether it supports to GPUs,

In [3]:
import torch
print("PyTorch version: ", torch.__version__)
print("GPU support: ", torch.cuda.is_available())
print("Available devices count: ", torch.cuda.device_count())

PyTorch version:  2.9.0+cu126
GPU support:  True
Available devices count:  1


## 2.2 Quick start - Tensor in PyTorch

In this section, we introcue some basic concepts and operations of Tensor.

In [4]:
import numpy as np

Tensors are a specialized data structure that are very similar to arrays and matrices. In PyTorch, we use tensors to encode the inputs and outputs of a model, as well as the model’s parameters.

Tensors are similar to NumPy’s ndarrays, except that tensors can run on GPUs or other hardware accelerators.

### Create Tensors

Tensors can be created directly from data or NumPy arrays. You can assign the data type to the tensor. Otherwise, the data type would be automatically inferred.

In [5]:
data = [[0,1], [2,3]]
tensor_data = torch.tensor(data)
tensor_data_float = torch.tensor(data).float()
print(f"Long Tensor: \n {tensor_data} \n")  # the data type is LongTensor
print(f"Float Tensor: \n {tensor_data_float} \n")

Long Tensor: 
 tensor([[0, 1],
        [2, 3]]) 

Float Tensor: 
 tensor([[0., 1.],
        [2., 3.]]) 



In [6]:
np_data = np.array(data)
tensor_np_data = torch.tensor(np_data)
tensor_np_data_float = torch.tensor(np_data).float()
print(f"Long Tensor: \n {tensor_np_data} \n")  # the data type is LongTensor
print(f"Float Tensor: \n {tensor_np_data_float} \n")

Long Tensor: 
 tensor([[0, 1],
        [2, 3]]) 

Float Tensor: 
 tensor([[0., 1.],
        [2., 3.]]) 



You can also create the tensors filled with constant (e.g., 0 and 1) or random values,

In [8]:
zeros_tensor = torch.zeros((4,3))
ones_tensor = torch.ones((2,3))
random_tensor = torch.rand((4,3))
print(f"Zeros Tensor: \n {zeros_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Random Tensor: \n {random_tensor} \n")

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Random Tensor: 
 tensor([[0.7835, 0.7898, 0.2094],
        [0.8315, 0.8210, 0.6439],
        [0.9122, 0.1088, 0.4632],
        [0.7739, 0.1672, 0.7052]]) 



### Attributes of a Tensor

Tensor attributes describe their shape, datatype, and the device on which they are stored.

In [9]:
tensor = torch.rand(2,3)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([2, 3])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


### Operations on Tensors

There are over 100 tensor operations, including arthmetic, linear algebra, matrix manipulation and more. In this section, we only introduce some frequently used operations in our later tutorials and projects.

**Move Tensor to Device**

By default, tensors are created on the CPU. We need to explicitly move tensors to the GPU using `.to()` method (after checking for GPU availability). Keep in mind that copying large tensors across devices can be expensive in terms of time and memory!

In [10]:
# move tensor to GPU if available
device = "cuda" if torch.cuda.is_available() else "cpu"
tensor = tensor.to(device)
print(f"Device tensor is stored on: {tensor.device}")

Device tensor is stored on: cuda:0


**Tensor indexing, slicing and reshape**

In [11]:
tensor = torch.rand(4, 6)
tensor

tensor([[0.7850, 0.5206, 0.1081, 0.5861, 0.0546, 0.1521],
        [0.9825, 0.1869, 0.7760, 0.8527, 0.0657, 0.1522],
        [0.3314, 0.4537, 0.1966, 0.7626, 0.4249, 0.4441],
        [0.4008, 0.4176, 0.1130, 0.1167, 0.0398, 0.4893]])

In [13]:
# let take a look at its first row and column
print(f"First row: {tensor[0]}")
print(f"First column: {tensor[:,1]}")
print(f"Last column: {tensor[:, -1]}")

First row: tensor([0.7850, 0.5206, 0.1081, 0.5861, 0.0546, 0.1521])
First column: tensor([0.5206, 0.1869, 0.4537, 0.4176])
Last column: tensor([0.1521, 0.1522, 0.4441, 0.4893])


In [14]:
# reshape
print(f"Reshape to (2,12): \n {tensor.view(2, 12)} \n")
print(f"Reshape to (2,2,6): \n {tensor.view(-1, 2, 6)} \n")

Reshape to (2,12): 
 tensor([[0.7850, 0.5206, 0.1081, 0.5861, 0.0546, 0.1521, 0.9825, 0.1869, 0.7760,
         0.8527, 0.0657, 0.1522],
        [0.3314, 0.4537, 0.1966, 0.7626, 0.4249, 0.4441, 0.4008, 0.4176, 0.1130,
         0.1167, 0.0398, 0.4893]]) 

Reshape to (2,2,6): 
 tensor([[[0.7850, 0.5206, 0.1081, 0.5861, 0.0546, 0.1521],
         [0.9825, 0.1869, 0.7760, 0.8527, 0.0657, 0.1522]],

        [[0.3314, 0.4537, 0.1966, 0.7626, 0.4249, 0.4441],
         [0.4008, 0.4176, 0.1130, 0.1167, 0.0398, 0.4893]]]) 



**Joining tensors.** You can use torch.cat to concatenate a sequence of tensors along a given dimension.

In [15]:
t1 = torch.zeros(4, 2)
new_t = torch.cat([tensor, t1, t1], dim=1)
new_t

tensor([[0.7850, 0.5206, 0.1081, 0.5861, 0.0546, 0.1521, 0.0000, 0.0000, 0.0000,
         0.0000],
        [0.9825, 0.1869, 0.7760, 0.8527, 0.0657, 0.1522, 0.0000, 0.0000, 0.0000,
         0.0000],
        [0.3314, 0.4537, 0.1966, 0.7626, 0.4249, 0.4441, 0.0000, 0.0000, 0.0000,
         0.0000],
        [0.4008, 0.4176, 0.1130, 0.1167, 0.0398, 0.4893, 0.0000, 0.0000, 0.0000,
         0.0000]])

**Arithmetic operations**

The basic arithmetic operations of Pytorch are similar with those in Numpy, such as `.pow()`, `.div()`, `.sum()` and more. Here we talk more about multiplication in Pytorch.

In [ ]:
# This computes the matrix multiplication between two tensors. y1, y2 will have the same value
print(f"Shape of original tensor: {tensor.shape}")
y1 = tensor @ tensor.T
y2 = tensor.matmull(tensor.T)

print(f"Shape of matrix multiplication resulting tensor: {y1.shape}")

# This computes the element-wise product. z1, z2, z3 will have the same value
z1 = tensor * tensor
z2 = tensor.mul(tensor)

print(f"Shape of element-wise product resulting tensor: {z1.shape}")

In [ ]:
y1 = [[1, 2, 3],[2, 4 ,6]]

## 2.3 Practice

In NLP, we have a very popular and famous techique, termed **Attention** which is used to measure the improtance among each components. Formally, we define the attention mechanism as:

$Attention(\mathbf{Q},\mathbf{K},\mathbf{V}) = \text{Softmax}(\frac{\mathbf{Q}\mathbf{K}^T}{\sqrt{d_k}})\mathbf{V}$

$\text{Softmax}(x_{i}) = \frac{\exp(x_i)}{\sum_j \exp(x_j)}$,

you can attempt to implement softmax function and attention by yourself.

In [ ]:
v= torch.rand((2,4,8))
k = v
q = torch.rand((2,4,8))
d_k = 8

In [ ]:
# insert your code
def softmax(x, dim=0):
    pass

def attention(q, k, v):
    pass

**Hint** You may use some helpful functions or libraries: **torch.bmm(), math...**.